/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiSameMachine;

import SinglePlayerUI.GameMenu;
import db.DbConnector;
import db.Person;
import db.PersonDAC;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import SinglePlayerUI.HighScores;
import audio.Sound;
import multiPlayerUI.TypeOfMultiPlayer;
import org.apache.log4j.Logger;
/**
 *
 * @author Malith
 */
public class GameMenueMulti extends javax.swing.JFrame {
    private boolean loading1;
    private boolean loading2;
    Logger logger;
    /**
     * Creates new form GameMenueMulti
     */
    public GameMenueMulti() {
        initComponents();
        setLocationRelativeTo(null);
        this.loading1 = false;
        this.loading2 = false;
        logger=Logger.getLogger(GameMenueMulti.class);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLoadPlayer1 = new javax.swing.JButton();
        btnLoadPlayer2 = new javax.swing.JButton();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnPlayer1New = new javax.swing.JButton();
        btnPlayer2New = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe 2015");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 40));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 40));

        btnLoadPlayer1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnLoadPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadPlayer1.setText("Load Player");
        btnLoadPlayer1.setBorder(null);
        btnLoadPlayer1.setContentAreaFilled(false);
        btnLoadPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPlayer1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 25));

        btnLoadPlayer2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnLoadPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadPlayer2.setText("Load Player");
        btnLoadPlayer2.setBorder(null);
        btnLoadPlayer2.setContentAreaFilled(false);
        btnLoadPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPlayer2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, 25));
        getContentPane().add(txtPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 30));
        getContentPane().add(txtPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 30));

        btnStart.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.setBorder(null);
        btnStart.setContentAreaFilled(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 170, 60));

        btnPlayer1New.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnPlayer1New.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayer1New.setText("Add New Player");
        btnPlayer1New.setBorder(null);
        btnPlayer1New.setContentAreaFilled(false);
        btnPlayer1New.setFocusPainted(false);
        btnPlayer1New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1NewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayer1New, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 30));

        btnPlayer2New.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnPlayer2New.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayer2New.setText("Add New Player");
        btnPlayer2New.setBorder(null);
        btnPlayer2New.setContentAreaFilled(false);
        btnPlayer2New.setFocusPainted(false);
        btnPlayer2New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2NewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayer2New, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 40));

        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 81, 41));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Headmini.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/BlackWodBig.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
      new Thread(new Sound("click.wav")).start();
        String player1Name = txtPlayer1.getText();
       String player2Name = txtPlayer2.getText();
       
       if(player1Name.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter Player1 name or load", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       if( player2Name.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter Player2 name or load", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       if(player1Name.equals(player2Name)){
           JOptionPane.showMessageDialog(this, "Players should be different!", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        
        try {
            DbConnector dbConnector = new DbConnector();
            PersonDAC personDAC = new PersonDAC(dbConnector.getMyConn());

           if(!loading1) {
                personDAC.addPerson(new Person(player1Name, 0, 0, 0, 0, 0, 0, 0, 0));
                
            }
           if(!loading2) {              
                personDAC.addPerson(new Person(player2Name, 0, 0, 0, 0, 0, 0, 0, 0));
                
            }
            personDAC.close(dbConnector.getMyConn(), null, null);

        } catch (IOException ex) {
            //Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "This User name is already taken, please chose a different name", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            txtPlayer1.setText(null);
            txtPlayer2.setText(null);
           // Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        this.dispose();
        logger.info(txtPlayer1+" and "+txtPlayer2 +" start the game");
        Console console = new Console(txtPlayer1.getText(), txtPlayer2.getText());
        
    }//GEN-LAST:event_btnStartActionPerformed

    public JTextField getTxtPlayer1() {
        return txtPlayer1;
    }

    public JTextField getTxtPlayer2() {
        return txtPlayer2;
    }

    
    
    private void btnLoadPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPlayer1ActionPerformed
       new Thread(new Sound("click.wav")).start();
        new HighScores(txtPlayer1).setVisible(true);
       loading1 = true;
       
       
    }//GEN-LAST:event_btnLoadPlayer1ActionPerformed

    private void btnLoadPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPlayer2ActionPerformed
        new Thread(new Sound("click.wav")).start();
        new HighScores(txtPlayer2).setVisible(true);
        loading2 = true;
       
    }//GEN-LAST:event_btnLoadPlayer2ActionPerformed

    private void btnPlayer1NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1NewActionPerformed
        new Thread(new Sound("click.wav")).start();
        loading1 = false;
        txtPlayer1.setText(null);
        txtPlayer1.setEnabled(true);
    }//GEN-LAST:event_btnPlayer1NewActionPerformed

    private void btnPlayer2NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2NewActionPerformed
        new Thread(new Sound("click.wav")).start(); 
        loading2 = false;
        txtPlayer2.setText(null);
        txtPlayer2.setEnabled(true);
    }//GEN-LAST:event_btnPlayer2NewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Thread(new Sound("click.wav")).start();
        dispose();
        new TypeOfMultiPlayer().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenueMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenueMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenueMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenueMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMenueMulti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadPlayer1;
    private javax.swing.JButton btnLoadPlayer2;
    private javax.swing.JButton btnPlayer1New;
    private javax.swing.JButton btnPlayer2New;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables
}
